import Head from 'next/head';
import { useContext } from "react";
import { useRouter } from 'next/router';
import React, { useState, useEffect } from "react";
import { AuthContext } from "../../client/context/AuthContext";

export default function Home() {
  const router = useRouter();
  const { auth, setAuth } = useContext(AuthContext);

  useEffect(async () => {
    try {
      const resp = await fetch("http://localhost:5000/auth//isVerified", {
        method: "POST",
        headers: { token: localStorage.token },
      });

      const parseRes = await resp.json();

      parseRes === true ? router.push("/dashboard") : router.push("/login");
    } catch (err) {
      console.log(err);
    }
  }, []);

  useEffect(() => {
    auth ? router.push("/dashboard") : router.push("/login");
  }, [])

  return (
    <div className="container">
      <Head>
        <title>JWT Login/Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button
          className="btn btn-success btn-block"
          onClick={() => router.push("/register")}
        >
          Register
        </button>

        <button
          className="btn btn-success btn-block"
          onClick={() => router.push("/login")}
        >
          Login
        </button>
      </div>
    </div>
  );
}
